name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build . --file Dockerfile -t xuancanhit99/ma-stu-service:latest

      - name: Login into Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push tag to Docker Hub
        run: docker push xuancanhit99/ma-stu-service:latest